name: neucon
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.16
  - pytorch=1.13.0
  - torchvision=0.14.0
  - cudatoolkit=11.6
  - ipython
  - tqdm
  - numba
  - sparsehash  # dependency for torchsparse
  - pip
  - pip:
    - -r requirements.txt
    - git+https://github.com/mit-han-lab/torchsparse.git
