DATASET: 'sevenscenes_allfrag'
BATCH_SIZE: 1
SAVE_SCENE_MESH: True
LOGDIR: 'ckpt_7scenes_stairs'
SAVE_FREQ: 1
MODE: 'test'

TRAIN:
  PATH: '/hdd1/7scene/stairs'
  EPOCHS: 991
  N_VIEWS: 9
  LR: 3e-5
  N_WORKERS: 8
  LREPOCHS: '12,24,48:2'

TEST:
  PATH: '/hdd1/7scene/stairs'
  N_VIEWS: 9
  N_WORKERS: 1

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.05
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True #False
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True #False

  LW: [1.0, 0.8, 0.64]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5
